{% set name = "sqlalchemy" %}
{% set version = "2.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-{{ version }}.tar.gz
  sha256: 05b971ab1ac2994a14c56b35eaaa91f86ba080e9ad481b20d99d77f381bb6258

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - wheel
    - setuptools
  run:
    - python
    - greenlet !=0.4.17
    - importlib-metadata  # [py<38]
    - typing-extensions >=4.2.0

test:
  imports:
    - sqlalchemy
    - sqlalchemy.connectors
    - sqlalchemy.dialects
    - sqlalchemy.dialects.mssql
    - sqlalchemy.dialects.mysql
    - sqlalchemy.dialects.oracle
    - sqlalchemy.dialects.postgresql
    - sqlalchemy.dialects.sqlite
    - sqlalchemy.engine
    - sqlalchemy.event
    - sqlalchemy.ext
    - sqlalchemy.ext.asyncio
    - sqlalchemy.ext.declarative
    - sqlalchemy.orm
    - sqlalchemy.sql
    - sqlalchemy.testing
    - sqlalchemy.testing.plugin
    - sqlalchemy.util
  requires:
    - pip
  commands:
    - pip check
  #downstreams:
    #- celery 5.0.5 # failed
    #- clickhouse-sqlalchemy 0.1.6 # failed
    # - flask-appbuilder 4.1.4 # failed
    # - flask-sqlalchemy 3.0.2 # succeeded
    # - geoalchemy2 0.9.2 # uses sqlalchemy:      1.4.39
    # - jupyterhub 3.1.1 # succeeded
    # - marshmallow-sqlalchemy 0.26.1 # succeeded
    # - sqlalchemy-jsonfield 1.0.0 # succeeded
    # - sqlalchemy-utils 0.41.1 # succeeded
    # - zope.sqlalchemy 2.0 # failed
    #- agate-sql 0.5.8 # succeeded
    #- airflow 2.4.3 # failed
    #- alembic 1.8.1 # succeeded
    #- asyncpgsa 0.27.1 # failed  (doesn't exist)
    #- blaze 0.11.3 # failed  (doesn't exist)
    #- ibis-framework 1.3.0 # failed  (doesn't exist)
    #- ipython-sql 0.3.9 # succeeded
    #- kombu 4.6.3 # failed
    #- mlflow 2.6.0 # succeeded
    #- pandasql 0.7.3 # succeeded
    #- pydruid 0.6.2 # failed  (doesn't exist)
    #- pyhive 0.6.1 # succeeded
    #- pyomniscidb 5.7.0  # failed  (doesn't exist)

about:
  home: https://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Database Abstraction Library.
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: https://docs.sqlalchemy.org/
  dev_url: https://github.com/sqlalchemy/sqlalchemy

extra:
  recipe-maintainers:
    - ocefpaf
    - mcs07
    - nehaljwani
    - igortg
