{% set name = "sqlalchemy" %}
{% set version = "2.0.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SQLAlchemy/sqlalchemy-{{ version }}.tar.gz
  sha256: 5d2d1fe548def3267b4c70a8568f108d1fed7cbbeccb9cc166e05af2abc25c22

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - wheel
    - setuptools
  run:
    - python
    - greenlet !=0.4.17  # [py<314]
    - importlib-metadata  # [py<38]
    - typing-extensions >=4.6.0

test:
  imports:
    - sqlalchemy
    - sqlalchemy.connectors
    - sqlalchemy.dialects
    - sqlalchemy.dialects.mssql
    - sqlalchemy.dialects.mysql
    - sqlalchemy.dialects.oracle
    - sqlalchemy.dialects.postgresql
    - sqlalchemy.dialects.sqlite
    - sqlalchemy.engine
    - sqlalchemy.event
    - sqlalchemy.ext
    - sqlalchemy.ext.asyncio
    - sqlalchemy.ext.declarative
    - sqlalchemy.orm
    - sqlalchemy.sql
    - sqlalchemy.testing
    - sqlalchemy.testing.plugin
    - sqlalchemy.util
  requires:
    - pip
    - pytest >=7,<8.2
    - pytest-xdist
    - mypy >=1.7.0
    - sqlite
  source_files:
    - pyproject.toml
    - setup.cfg
    - examples
    - lib
    - test
  commands:
    - pip check
    # Error with test teardown closing sqlite database on python > 3.10 in a conda env.
    - pytest -n8 test -m "not backend" -k "not (aaa_profiling or test_pickle_rows_other_process)"  # [py<=310]
    - pytest -n8 test -m "backend" -k "not (aaa_profiling or test_pickle_rows_other_process)"

about:
  home: https://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Database Abstraction Library.
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: https://docs.sqlalchemy.org/
  dev_url: https://github.com/sqlalchemy/sqlalchemy

extra:
  recipe-maintainers:
    - ocefpaf
    - mcs07
    - nehaljwani
    - igortg
