{% set name = "sqlalchemy" %}
{% set version = "1.4.51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-{{ version }}.tar.gz
  sha256: e7908c2025eb18394e32d65dd02d2e37e17d733cdbe7d78231c2b6d7eb20cdb9

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - wheel
    - setuptools
  run:
    - python
    - greenlet !=0.4.17
    - importlib-metadata  # [py<38]

test:
  imports:
    - sqlalchemy
    - sqlalchemy.connectors
    - sqlalchemy.dialects
    - sqlalchemy.dialects.mssql
    - sqlalchemy.dialects.mysql
    - sqlalchemy.dialects.oracle
    - sqlalchemy.dialects.postgresql
    - sqlalchemy.dialects.sqlite
    - sqlalchemy.engine
    - sqlalchemy.event
    - sqlalchemy.ext
    - sqlalchemy.ext.asyncio
    - sqlalchemy.ext.declarative
    - sqlalchemy.orm
    - sqlalchemy.sql
    - sqlalchemy.testing
    - sqlalchemy.testing.plugin
    - sqlalchemy.util
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Database Abstraction Library.
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: https://docs.sqlalchemy.org/
  dev_url: https://github.com/sqlalchemy/sqlalchemy

extra:
  recipe-maintainers:
    - ocefpaf
    - mcs07
    - nehaljwani
    - igortg
