# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "E0q1N1BgMWNx90s5zijSLeRqq2kg9cm2OSg+ugWpkh3LaAp09LJx9fcCHwgufOwpXQPFHemAhnJZXqGnWviVcuhgnI5J+EW01KFTgFWiXmRibwMftpTU10VptR9Zv2Y8ro5nPBSTMsbfWIucl3aocZdwUggdeQdCA+7B0WF1iWgmJ5CksjtM/R1Ly9AoV0U2yYVlDmtmbtg+ILNKuplDvf7YLXgueLbmMsEAvHPOati8rvju3ArGOuYU2OPwQWv6V4cFT2cqUT53TPd0maNvxZ1pYqBUYxpIR8bCP3kMyK8pvvNmURwhfR9Fet88/pBzbbn8E36a49cYlS5ar69F4LSVQ14H9o+LzwTISyyJ0ng5X78Umw0/44TyBjrnI+QnGmXLZXapT9ALQCuXjwwrGSg/bentpoz3rCNJ745plpAufmk+ONJzzJly5u54x1igYPqzlKLhQIjthh1SiFW0ggiOWgqUTXC+fKrsDzw+REQ7aF8P/JMI8B79KK2YBOVFBqP7dGmus/wwbSfKEzucBBnlix3d+67QA/3tLgFO4WuFB36HwyYVV/D85oDsyrABEKnEySoWGz9rKsGMgisp/PnqvQ5dfZxAufpL+ozf2EHyl7wyaXejCzWvKPSHSNgKAsoYEfs96sm5w7sL4QQOytyZss1EouqwWZHWTnL6e9w="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml