travis:
  secure:
    BINSTAR_TOKEN: d51Bs0C1IwyuMMElyGGRsDowgVhjoHmjMTQnPZwDaTHg4WtnU+gOWuhtPXgwhz1BuwtcOqvRt+AWfTl2b/wysiSDYCi0MblmqdOGW20e1aBw8lNBsednAv2ayo7Wi8KPuLNRLkxaLMea0UffILKDaIirqC+ACfTYMLzCKwXup7fgccHxS80NxdJkn5O0kW+YSNaZAQNVhCVnfU4Crxer6rjXZEQOj6ss4QdCaz2t2i2CMHsyRqeCu5OALc63hyVBcy8ocQj1ELoBMbNv462AeOgZeIhkWoGCOPi66rzX0n2nzGtImEaR0jqjhLc0up0o9TlOy4vbIr77vwBFCeuYO6wK1lsUOFFGE7k7NQkSLYupRlRQcKN5igKYNT74Rv1LLiZxJyTVfANcuok1JiqV+RwSuwmt6J/uqt62LgiAIbS6j4IuJ5WJhde8ZBMmY2x/RiMGrUyH6ouY4tzG72vOeqVsnp+pqNBzyg7iQjcA76bBR/0Eehtsjya16IYqhoZfEKEM7lWzeQbmgk8AwbpnRsJb5Kxv65mBss/jOJ/rMUnstmLqZteLlBzi7dC/Y3biRhjXeEqlKW1B5bH/5zSgnRDkc8yJepcEmXlTiwFOK7KKx5vg7fZtentZt++BTHB5+PuKYlaOPCBkAIBDtGRiVxoVx3j4rgKU6y1FJxLQ4YM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
